name:
  en: DooTask MCP Server
  zh: DooTask MCP 服务
description:
  en: Expose the DooTask MCP toolset as a standalone service that works with Claude and other MCP-compatible assistants.
  zh: 将 DooTask MCP 工具集以独立服务形式对外提供，可被 Claude 等支持 MCP 协议的助手使用。
tags:
  - MCP
  - AI
  - Automation
author: DooTask
website: https://www.dootask.com
github: https://github.com/dootask/mcp
document: https://docs.dootask.com/
fields:
  - name: MCP_PORT
    label:
      en: MCP Port
      zh: MCP 端口
    description:
      en: Container port exposed by the MCP server.
      zh: MCP 服务监听的容器端口。
    type: number
    default: 7000
  - name: HEALTH_PORT
    label:
      en: Health Port
      zh: 健康检查端口
    description:
      en: Internal port used for health checks inside the container.
      zh: 容器内部用于健康检查的端口。
    type: number
    default: 7001
  - name: REQUEST_TIMEOUT
    label:
      en: Request Timeout (ms)
      zh: 请求超时时间（毫秒）
    description:
      en: Maximum time in milliseconds to wait for DooTask API responses.
      zh: 调用 DooTask 接口时的最大等待时间（毫秒）。
    type: number
    default: 30000
menu_items:
  - location: application
    label:
      en: MCP Usage Guide
      zh: MCP 使用指南
    url: /
    url_type: iframe
