name:
  en: MCP Server
  zh: MCP 服务
description:
  en: Expose MCP toolset as a standalone service for Claude and MCP-compatible assistants.
  zh: 将 MCP 工具集作为独立服务提供给 Claude 等助手使用。
tags:
  - MCP
  - AI
  - Automation
author: DooTask
github: https://github.com/dootask/mcp
