name: Release

# 需要配置的变量
# DOOTASK_USERNAME
# DOOTASK_PASSWORD
# DOCKER_USERNAME
# DOCKER_PASSWORD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Create dootask-plugin tar.gz package
        run: |
          cd dootask-plugin
          mv 0.0.1 ${{ github.ref_name }}
          tar -czf ../dootask-plugin.tar.gz .
          cd ..
          echo "Package created: dootask-plugin.tar.gz"
          ls -la dootask-plugin.tar.gz

      - name: Publish to DooTask App Store
        id: publish
        uses: dootask/appstore-action@v2
        with:
          username: ${{ secrets.DOOTASK_USERNAME }}
          password: ${{ secrets.DOOTASK_PASSWORD }}
          appid: 'mcp'
          package_file: './dootask-plugin.tar.gz'
          draft: false